name = "zed"
age = 22
is_student = True
weight = 95

print("Name :", name)
print("Rata type of name is", type(name))

print("Age", age)
print("Data type of name is", type(age))

print("is_student", is_student)
print("Data type of is_student is", type(is_student))

print("weight", weight)
print("Data type of weight is", type(weight))

print("\n After Type Casting...." )
age=str(age)
print(age)
print("Data type of age is", type (age))
weight = int(weight)
print(weight)
print("Data type of weight is", type(weight))